version: 2
jobs:
  build_and_test:
    working_directory: ~/trello
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  

  build_and_push_docker_container:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t herrickz/trello-frontend:$CIRCLE_BRANCH .

      - run: docker push herrickz/trello-frontend:$CIRCLE_BRANCH

workflows:
  version: 2
  build_test_push_docker_container:
    jobs:
      - build_and_test
      - build_and_push_docker_container:
          requires:
            - build_and_test
          filters:
            branches:
              only: master